#!/bin/bash

if [[ $1 == "update" ]]; then
  echo "Pulling the latest Docker image..."
  docker pull ghcr.io/mjason/luo:latest
fi

echo "Running the Docker container..."

docker run --rm -it \
  -p 8888:8888 \
  -v "$PWD:/workdir" \
  ghcr.io/mjason/luo:latest \
  "$@"
