#!/bin/bash

if [ -z "$(ls -A $PWD/bundle_gems)" ]; then
  docker run --rm -v "$PWD/bundle_gems:/usr/local/bundle_1" --entrypoint sh ghcr.io/mjason/luo:latest /bin/sh
fi

docker run --rm -it \
  -v "$PWD:/workdir" \
  -v "$PWD/bundle_gems:/usr/local/bundle/" \
  ghcr.io/mjason/luo:latest \
  "$@"
