module Luo
  class Agent
    @action_input: untyped
    @context: AgentRunnerContext

    attr_reader self.agent_desc: String
    attr_reader self.agent_name: String

    def self.on_call_with_final_result: -> untyped

    attr_reader action_input: untyped
    attr_reader context: AgentRunnerContext

    def initialize: (AgentRunnerContext) -> untyped

    def self.create_parameter_method: -> untyped

    def self.on_call: -> untyped

    attr_reader input: String
    attr_reader row_input: String?
  end
end
