module Luo
  class Messages
    @history: Array[Hash[Symbol, String]]
    @messages: Array[Hash[Symbol, String]]
    @system: Hash[Symbol, String]

    def self.create: -> Messages

    def self.create_role_message_method: -> untyped

    def self.create_role_message_methods: -> untyped

    def assistant: -> Messages
    def system: -> Messages

    def to_a: -> Array[Hash[Symbol, String]]

    def user: -> Messages
  end
end
