module Luo
  class PromptTemplate
    @file_path: String?
    @template: ERB

    def self.create: -> PromptTemplate

    def self.load_template: -> PromptTemplate

    def render: -> string

    def result: -> String

    private

    def context_binding: -> untyped
  end
end
